### ISSUE TITLE
[Question] Dynamic values in SEO tags

### ISSUE THREAD

**Issue by rajakhoury** [mariavilaro/october-plugin-mlseo#3]
Hi Maria, great plugin - Simple and gets the job done!

I'd like to have dynamic values in my SEO tags, for example in a CMS page : 

	url = "/prueba/establecimientos/:venueSlug|^[a-z0-9\-]+$"
	[viewBag]
	localeUrl[en] = "/test/venues/:venueSlug|^[a-z0-9\-]+$"

then in the Seo component I can set the titles in both locales : 

	Title in ES for venue...
	Title in EN for venue...

So far everything works as expected but I'd like to append extra info to these dynamic pages such as the venue's Name ect...

My approach was to add a placeholder in the translated strings : 

	Title in EN for venue %venueName%

and replace the value during runtime in my component : 

    public function onRender()
    {
       $this->page->title = str_replace("%venueName%", $this->venue->name , $this->page->title )   ;
    }
 
What do you think about this approach ? Do you believe is there a better way to handle this ?

Again thanks alot!

**Comment by mariavilaro** [comment]
Hi! Honestly for solving this, I just add SEO fields in my models (so 'venues' table would have seo_title, seo_description, seo_image etc fields and user would manage them from the Venue plugin), but yes, it's a functionality I plan to add someday to MLSEO. This placeholder concept is interesting yes, I take note of it thank you!
